apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    type: result-service
    app: myapp
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: front-end_result
    app: myapp
