apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    type: postgres_service
    app: myapp
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: back-end_db
    app: myapp