apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    type: votingapp-service
    app: myapp
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: front-end
    app: myapp