apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    type: redis_service
    app: myapp
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    type: back-end_redis
    app: myapp