apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-worker
  labels:
    app: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      type: back-end
      app: myapp
  template:
    metadata:
      name: worker-pod
      labels:
        type: back-end
        app: myapp

    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
