apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-votingapp
  labels:
    app: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
      app: myapp
  template:
    metadata:
      name: votingapp-pod
      labels:
        type: front-end
        app: myapp

    spec:
      containers:
        - name: voting-app-ui
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80