apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-result
  labels:
    app: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end_result
      app: myapp
  template:
    metadata:
      name: result-pod
      labels:
        type: front-end_result
        app: myapp

    spec:
      containers:
        - name: result-app-ui
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80