apiVersion: v1
kind: Pod
metadata:
  name: votingapp_pod
  labels:
    type: front-end
    app: myapp

spec:
  containers:
    - name: voting-app-ui
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80