apiVersion: v1
kind: Pod
metadata:
  name: redis_pod
  labels:
    type: back-end_redis
    app: myapp

spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379