apiVersion: v1
kind: Pod
metadata:
  name: postgres_pod
  labels:
    type: back-end_db
    app: myapp

spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432